### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by unix2dos** [JulianSchoenbaechler/MicDecode-Unity#1]
// Every frame
	void Update()
	{
		// Display calculated values
		displayText.text =	"Volume: " + microphone.VolumeDecibel.ToString("F1") + "dB\n" +
							"Frequency: " + microphone.Frequency.ToString("F0") + "Hz\n";
	}

I got an error, NullReferenceException: Object reference not set to an instance of an object
how to fix it? thanks

**Comment by JulianSchoenbaechler** [comment]
Have you assigned the MicDecode and Text component in the inspector?
